POST http://localhost:3333/api/users
Content-Type: application/json

{
            "id":"2",
            "email": "juanazula@example.com",
            "password": "123456K*",
            "name": "juan",
            "movies":[],
            "series":[]
}