POST http://localhost:3333/api/series
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3MTIxMzY3NDAsImV4cCI6MTcxMjIyMzE0MH0.40nY60-bMJDljnmhez8c3GMXc8JXjWtaNpMQS4AVZ5o

{
  "title": "How I Met Your Mother",
  "description": "The epic comeback of Dominick Toreto",
  "releaseYear": 2043,
  "poster_img": "https://res.cloudinary.com/dgtamgaup/image/upload/v1710430305/ddx5zoocjndw9w70y2co.webp",
  "genresName": "comedy",
  "score": 7,
  "authorEmail":"user@example.com"
}