PATCH http://localhost:3333/api/movies/65f31881fd25437e379a420c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTA1MDA5ODMsImV4cCI6MTcxMTEwNTc4M30.qFH1xfwtWn-5Zrrx2V-xHuNdBcdMRhOY7sWW-431ewA

{

  "releaseYear": 2037

}